storage:
    hosts:
        - localhost:27017
    name: minecraft
    collection: players
general:
    restoreSessions: true
    playernamePattern: ^[a-zA-Z0-9_]+$
    maxPerIp: 1
messages:
   error_account_is_block: "&4Аккаунт заблокирован."
   error_account_is_auth: "&4Вы уже авторизованы."
   error_account_not_registred: "&4Игрок с таким именем не зарегистрирован."
   error_account_online: "&4Игрок с ником %s сейчас находится в игре."
   error_account_exists: "&4Игрок с таким именем уже зарегистрирован."
   error_account_register_limit: "&4Достигнут предел регистраций с вашего IP."
   error_input_password: "&4Введите пароль."
   error_input_password_new: "&4Введите новый пароль."
   error_input_passwords_equals: "&4Новый пароль такой же как и старый."
   error_input_playername: "&4Не указано имя игрока."
   error_input_password_missmach: "&4Неправильный пароль."
   error_input_invalid_login: "&4Имя игрока содержит неправильные символы."
   error_command_permission: "&4У вас недостаточно прав для выполнения этой комманды."
   error_command_sender: "&4Эта комманда работает только для игроков."
   success_account_create: "&2Регистрация завершена."
   success_account_logout: "&2Игровая сессия завершена."
   success_account_delete: "&2Игровой аккаунт удален."
   success_account_login: "&2Вы успешно авторизованы. Удачной игры!"
   success_change_password: "&2Пароль был изменен."
   success_command_admin_changepassword: "&2Пароль для игрока %s был изменён."
   success_command_admin_delete: "&2Аккаунт игрока %s был удален."
   success_command_admin_register: "А&2ккаунт %s зарегистрирован."
   command_register_hint: "Зарегистрируйтесь с помощью команды &a/register пароль"
   command_login_hint: "Авторизируйтесь с помощью команды &a/login пароль"

