database:
    host: localhost
    port: 27017
    name: minecraft
    collection: players
general:
    silentMode: true
    restoreSessions: true
    whitelist: false
    playernamePattern: ^[a-zA-Z0-9_]+$
    maxPerIp: 2
