name: ${artifactId}
main: ${groupId}.${artifactId}
author: Maxim Varentsov <admin@gtn-craft.ru>
version: ${version}
commands:
   login:
      description: Авторизоваться на сервере.
      usage: /<command> <пароль>
      aliases: [l]
   logout:
      description: Завершить игровую сессию.
      usage: /<command>
      permission: mongoauth.use
   register:
      description: Регистрация на сервере.
      usage: /<command> <пароль>
      aliases: [reg]
   unregister:
      description: Удалить игровой аккаунт.
      usage: /<command> <пароль>
      permission: mongoauth.use
   changepassword:
      description: Сменить пароль.
      usage: /<command> <пароль> <новый пароль>
      permission: mongoauth.use
      aliases: [changepass, cpw]
   mongoauth:
      description: Управление учетными записями.
      usage: |
         /<command> register <playername> <password> - Создать аккаунт.
         /<command> unregister <playername> - Удалить аккаунт.
         /<command> changepassword <playername> <password> - Сменить пароль.
         /<command> block <playername> <true|false> - Вкл|выкл блокировку аккаунта.
      permission: mongoauth.admin
permissions:
   mongoauth.admin:
      description: Gives an admin access
      default: op
   mongoauth.use:
      description: Allows the use of plugin to players
      default: true
