name: ${artifactId}
main: ru.gtncraft.mongoauth.MongoAuth
author: Maxim Varentsov <admin@gtn-craft.ru>
version: ${version}
commands:
   login:
      description: Авторизоваться на сервере
      usage: /login пароль
      aliases: [l]
   logout:
      description: Завершить игровую сессию
      usage: /logout
      permission: mongoauth.user
   register:
      description: Регистрация на сервере
      usage: /register пароль
   unregister:
      description: Удалить игровой аккаунт
      usage: /unregister пароль
      permission: mongoauth.user
   cpw:
      description: Сменить пароль
      usage: /cpw пароль новый_пароль
      permission: mongoauth.user
      aliases: [changepass]
   create:
      description: Управление учетными записями
      usage: |
         /<command> register <playername> <password> - Создать аккаунт.
         /<command> unregister <playername> - Удалить аккаунт.
         /<command> cpw <playername> <password> - Сменить пароль.
      permission: mongoauth.admin
permissions:
   mongoauth.admin:
      description: Gives an admin access
      default: op
   mongoauth.user:
      description: Allows the use of plugin to players
      default: true
